modLoader="javafml"
loaderVersion="[47,)"
license="LGPL-3.0"
issueTrackerURL="https://github.com/xiaocihua/stack-to-nearby-chests/issues"

[[mods]]
modId="stacktonearbychests"
version="${file.jarVersion}"
displayName="Stack to Nearby Chests (Unofficial Forge Port)"
description='''
Unofficial Forge port of the Fabric mod Stack to Nearby Chests by xiaocihua.
A client-side ONLY mod that adds quick stacking and restocking features from Terraria into Minecraft.
Original Fabric mod: https://github.com/xiaocihua/stack-to-nearby-chests
'''

# Client-only declarations (no server requirements)
displayURL="https://github.com/xiaocihua/stack-to-nearby-chests"
authors="xiaocihua (original), Forge port by dtbcds"

# Dependencies
[[dependencies.stacktonearbychests]]
modId="forge"
mandatory=true
versionRange="[47,)"
ordering="NONE"
side="CLIENT"

[[dependencies.stacktonearbychests]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1,1.20.2)"
ordering="NONE"
side="CLIENT"

[[dependencies.stacktonearbychests]]
modId="cloth_config"
mandatory=true
versionRange="[11.1.118,)"
ordering="NONE"
side="CLIENT"
